Feature: Added coordinateSearch parameter for LocationPicker.
digipolisantwerp/location-picker_widget_angular pull request #121
Opened 2024-04-08 12:15 UTC by DanielSavin2001

2024-04-09 07:14 UTC, NicolasYapla approved these changes

2024-04-09 07:23 UTC, ArthurCallant approved these changes

2024-04-09 07:24 UTC, yplarthur approved these changes

2024-04-16 06:53 UTC, TriangleJuice requested changes
Hey Daniel, ziet er al goed uit, maar kan je buiten mijn minimale opmerkingen nog tests schrijven voor de nieuwe functionaliteit? Alvast bedankt!

2024-04-16 06:53 UTC, TriangleJuice commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.ts
> +import {AddressModel, LatLngModel} from "../types/address.model";
Fix je nog even de spatiëring hier?

2024-04-16 06:53 UTC, TriangleJuice commented on projects/ngx-location-picker/src/lib/types/delegate-search.model.ts
> +import {AddressModel, LatLngModel} from '../../lib/types/address.model';
Ook hier graag spatiëren even in orde brengen.

2024-04-16 08:38 UTC, DanielSavin2001 commented
@TriangleJuice 

Ik heb lokaal de aanpassingen gemaakt, en zou je mij meer info kunnen geven over welke testen specifiek, want ik heb in de project eens gezien en ik zag geen gelijkaardige testen dat ik kon hergebruiken & bijsturen.

Wat & hoe moet er effectief getest worden?

2024-04-16 10:57 UTC, TriangleJuice commented
> @TriangleJuice
> 
> Ik heb lokaal de aanpassingen gemaakt, en zou je mij meer info kunnen geven over welke testen specifiek, want ik heb in de project eens gezien en ik zag geen gelijkaardige testen dat ik kon hergebruiken & bijsturen.
> 
> Wat & hoe moet er effectief getest worden?

Hey @DanielSavin2001 je kan bv. wat zaken door de 'buildAddressQuery' function van de helper service gooien en testen of de output naargelang de input telkens juist is.

2024-04-16 13:21 UTC, DanielSavin2001 commented
> > @TriangleJuice
> > Ik heb lokaal de aanpassingen gemaakt, en zou je mij meer info kunnen geven over welke testen specifiek, want ik heb in de project eens gezien en ik zag geen gelijkaardige testen dat ik kon hergebruiken & bijsturen.
> > Wat & hoe moet er effectief getest worden?
> 
> Hey @DanielSavin2001 je kan bv. wat zaken door de 'buildAddressQuery' function van de helper service gooien en testen of de output naargelang de input telkens juist is.

@TriangleJuice 

Testen zijn toegevoegd, het was zeker terechte feedback! 😄 

Ik wacht dan enkel nog op feedback ivm Icoontje: https://github.com/digipolisantwerp/location-picker_widget_angular/commit/7f5559fedcd0f2f721a8dfb72131867cb448ff12

2024-04-17 08:08 UTC, TriangleJuice approved these changes

2024-04-17 08:08 UTC, merged