Feature/gis 421
digipolisantwerp/location-picker_widget_angular pull request #52
Opened 2021-04-28 07:55 UTC by GlennDigipolis

2021-04-28 11:59 UTC, TriangleJuice requested changes
Nog enkele algemene opmerkingen:

- Misschien bij deze grotere update ineens ook de core branding naar de laatste versie brengen (v4.3.1).
- De NPM audit lijst begint al wat issues te geven. Misschien de gemakkelijke er al even uithalen?

2021-04-28 11:59 UTC, TriangleJuice commented on README.md
> +    */
Waarom deze indent change?

2021-04-28 11:59 UTC, TriangleJuice commented on angular.json
> +              "node_modules/leaflet.markercluster/dist/MarkerCluster.css"
Minor: bestaan hier geen cdn's voor?

2021-04-28 11:59 UTC, TriangleJuice commented on projects/ngx-location-picker/package.json
> +    "@acpaas-ui-widgets/ngx-location-viewer": "^1.2.0",
Dat mag ineens `"^1.3.0"` worden.

2021-04-28 11:59 UTC, TriangleJuice commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.scss
> +    margin-top: 3.75rem;
Welke controls zijn dit?

2021-04-28 13:54 UTC, GlennDigipolis commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.scss
> +    margin-top: 3.75rem;
Dit zijn de controls van location-viewer, anders overlap met location search input

2021-04-28 14:00 UTC, GlennDigipolis commented on package.json
> +    "ngx-location-viewer": "0.0.1-beta.2",
Dit stond van verkeerd van testen met eigen npm package

2021-04-28 16:31 UTC, GlennDigipolis commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.html
> +  <aui-location-viewer
Ok, vraag hierbij is nu geef ik de leaflet instance vanuit de picker mee door naar de viewer. Omdat zowel picker widget als viewer widget deze gebruiken. Hoe kan ik ervoor zorgen dat deze altijd beschikbaar is in de widget. Via ContentChild?

2021-04-28 18:27 UTC, jsebrech commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.html
> +  <aui-location-viewer
Dat is inderdaad wel een lastige. Sowieso moet je een handle naar de aui-location-viewer ophalen via ContentChild. Daarna zie ik 2 mogelijkheden:

1. van de aui-location-viewer instance de leafletMap property uitlezen en die gebruiken
2. op location-viewer zorg je dat de leafletMap on the fly veranderd kan worden, en aui-location-picker zet dan een nieuwe waarde voor leafletMap op de viewer

2021-05-17 12:28 UTC, GlennDigipolis commented on projects/ngx-location-picker/src/lib/components/ngx-location-picker.component.html
> +  <aui-location-viewer
Nadat ik dit heb bekeken en even nagevraagd bij jullie. Leek hiervoor niet direct een gepast oplossing, vanwege de content projection van location-picker logica naar location-viewer.

2021-06-09 07:06 UTC, jsebrech approved these changes
voor mij ok indien het voor jasper ok is

2021-06-09 07:31 UTC, TriangleJuice approved these changes
All minor remarks. Please review and fix where necessary ;-)

2021-06-09 07:31 UTC, TriangleJuice commented on README.md
> +     @Input() featureLayers: FeatureLayerModel[] = [];
Vreemde indent hier

2021-06-09 08:39 UTC, GVissers27 commented on angular.json
> +              "node_modules/leaflet.markercluster/dist/MarkerCluster.css"
Ja hier zijn CDN's voor maar kan dit mogelijk geen fouten geven als dit niet matched met de installed version via npm?

2021-06-09 09:00 UTC, TriangleJuice commented on angular.json
> +              "node_modules/leaflet.markercluster/dist/MarkerCluster.css"
Het was een open vraag. Normaal kan je zelfs via CDN versie-nummers kiezen, maar je mag het van mij ook zo laten.

2021-06-09 14:24 UTC, merged